### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by sahlminkok** [sahlminkok/catalog-of-my-things#21]
- [GitHub Project Link](https://github.com/sahlminkok/catalog-of-my-things/projects/1)
- In this team, there are two assigned peers to this project
- the tasks assigned to each member are:
  - `Team member #1` assigned to @ProgramKingAbel 
  - `Team member #2` assigned to @sahlminkok 
  - `Team member #3` split to both peers

**Comment by mikethreels** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job setting up the board

## Required Changes ♻️
- [ ] According to the requirements there should be a card for each task on the requirements list, I see you have combined some of the tasks into 1 card, for example, for the group tasks there should be the following cards (naming can be different):
Make sure to do this for each team member as well.
    - Create Item class in a separate .rb file.
    - All Item class properties visible in the diagram should be defined and set up in the constructor method. 
    - Add all methods visible in the diagram.
    - Implement methods
    - Create a main.rb file that will serve as your console app entry-point.
    - Implement startup actions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sahlminkok** [comment]
Rearrange the tasks in the Kanban Board

**Comment by ichala** [comment]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
